Med322/Controllers/LoginController.cs
using Med322.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

namespace MiniPro322.Controllers
{
    public class LoginController : Controller
    {
        private readonly string apiUrl;
        private readonly HttpClient httpClient = new HttpClient();
        public LoginController(IConfiguration _config)
        {
            apiUrl = _config["ApiUrl"];
        }

        public IActionResult Index()
        {
            VMUser data = new VMUser();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> LoginVerification(VMUser inputLogin)
        {
            try
            {
                int userLoginId = 0;

                VMResponse? apiUserResponse = JsonConvert.DeserializeObject<VMResponse>(
                    await httpClient.GetStringAsync(apiUrl + "User/GetAll"));

                if (apiUserResponse == null)
                {
                    HttpContext.Session.SetString("ErrMsg", "Api Connection Error!");
                    throw new ArgumentNullException($"Failed to get user data due API connection error");
                }

                if (apiUserResponse.Success || apiUserResponse.data != null)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiUserResponse.Message);
                }
                else
                { throw new ArgumentNullException($"Failed to get user data"); }

                List<VMUser>? dataUsers = JsonConvert.DeserializeObject<List<VMUser>>(apiUserResponse.data.ToString());

                foreach (VMUser dataUser in dataUsers)
                {
                    if ((inputLogin.Email == dataUser.Email) && (inputLogin.Password == dataUser.Password))
                    {
                        userLoginId = (int)dataUser.Id;
                    }

                }

                if (userLoginId == 0)
                {
                    HttpContext.Session.SetString("ErrMsg", "Email atau Password salah");
                    return Json(new { success = false });
                }

                VMResponse? apiLoginResponse = JsonConvert.DeserializeObject<VMResponse>(
                    await httpClient.GetStringAsync(apiUrl + "Userdata/" + userLoginId));

                if (apiLoginResponse == null)
                {
                    HttpContext.Session.SetString("ErrMsg", "Api Connection Error!");
                    throw new ArgumentNullException($"Failed to get user data due API connection error");
                }

                if (apiLoginResponse.Success || apiLoginResponse.data != null)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiLoginResponse.Message);
                }
                else
                { throw new ArgumentNullException($"Failed to get user data"); }

                VMUserData? SessionData = JsonConvert.DeserializeObject<VMUserData>(apiLoginResponse.data.ToString());

                HttpContext.Session.SetString("UserID", SessionData.UserId.ToString() ?? "0");
                HttpContext.Session.SetString("BiodataID", SessionData.BiodataId.ToString() ?? "0");
                HttpContext.Session.SetString("RoleID", SessionData.RoleId.ToString() ?? "0");
                HttpContext.Session.SetString("RoleName", SessionData.RoleName ?? "Guest");
                HttpContext.Session.SetString("FullName", SessionData.Fullname ?? "Guest");
                HttpContext.Session.SetString("ImagePath", SessionData.ImagePath ?? "");
                HttpContext.Session.SetString("DoctorId", SessionData.DoctorId.ToString() ?? "0");

                //if (HttpContext.Session.GetString("RoleName") == "Patient")
                //{
                //    return RedirectToAction("Index", "Patient");
                //}
                //else if (HttpContext.Session.GetString("RoleName") == "Dokter")
                //{
                //    return RedirectToAction("Index", "Doctor");
                //}
                //else if (HttpContext.Session.GetString("RoleName") == "Admin")
                //{
                //    return RedirectToAction("Index", "Admin");
                //}
                //else
                //{
                //    return RedirectToAction("Index", "Guest");
                //}
                return Json(new { success = true, redirectToUrl = Url.Action("Index", SessionData.RoleName) });
            }
            catch (Exception e)
            {
                HttpContext.Session.SetString("ErrMsg", e.Message);
                return Json(new { success = false });
            }

        }
        public IActionResult SignIn()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.SetString("UserID", string.Empty);
            HttpContext.Session.SetString("BiodataID", string.Empty);
            HttpContext.Session.SetString("RoleID", string.Empty);
            HttpContext.Session.SetString("RoleName", string.Empty);
            HttpContext.Session.SetString("FullName", string.Empty);
            HttpContext.Session.SetString("ImagePath", string.Empty);
            HttpContext.Session.SetString("DoctorId", string.Empty);

            return RedirectToAction("Index", "Redirect");
        }
    }
}

Med322/Controllers/ProfilePatientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using System.Text;
using Med322.ViewModels;
using System.Net.Http;
using System;

namespace Med322.Controllers
{

    public class ProfilePatientController : Controller
    {
        private readonly string apiUrl;
        private readonly HttpClient httpClient = new HttpClient();
        public ProfilePatientController(IConfiguration _config)
        {
            apiUrl = _config["ApiUrl"];
        }
        public async Task<IActionResult> Index()
        {

            try
            {
                int Id = int.Parse(HttpContext.Session.GetString("BiodataID"));

                VMResponse? apiCustomerIdResponse = JsonConvert.DeserializeObject<VMResponse>(
                    await httpClient.GetStringAsync(apiUrl + "Customer/GetCustomerId/" + Id));


                if (apiCustomerIdResponse == null)
                {
                    throw new ArgumentNullException($"Failed get Customer data ID and API connection Error");
                }

                if (apiCustomerIdResponse.data != null || apiCustomerIdResponse.Success)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiCustomerIdResponse.Message);
                }
                else
                {
					HttpContext.Session.SetString("ErrMsg", apiCustomerIdResponse.Message);
					VMPatientProfile? dataNull = new VMPatientProfile();

					VMResponse? apiUserNullResponse = JsonConvert.DeserializeObject<VMResponse>(
	                await httpClient.GetStringAsync(apiUrl + "User/" + Id));

					ViewBag.Account = JsonConvert.DeserializeObject<VMUser>(apiUserNullResponse.data.ToString());

					return View(dataNull);
				}
                VMCustomer? customerId = JsonConvert.DeserializeObject<VMCustomer>(apiCustomerIdResponse.data.ToString());

                VMResponse? apiBiodataResponse = JsonConvert.DeserializeObject<VMResponse>(
                                    await httpClient.GetStringAsync(apiUrl + "PatientProfile/" + customerId.Id));

                //VMResponse? apiUserResponse = JsonConvert.DeserializeObject<VMResponse>(
                //    await httpClient.GetStringAsync(apiUrl + "User/" + Id));
                int IdU = int.Parse(HttpContext.Session.GetString("UserID"));

                VMResponse? apiUserResponse = JsonConvert.DeserializeObject<VMResponse>(
                    await httpClient.GetStringAsync(apiUrl + "User/" + IdU));

                if (apiBiodataResponse == null || apiUserResponse == null)
                {
                    throw new ArgumentNullException($"Failed get Patient Profile data ID = {Id} and API connection Error");
                }

                if (apiBiodataResponse.data != null || apiBiodataResponse.Success || apiUserResponse != null || apiUserResponse.Success)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiBiodataResponse.Message);
                }
                else
                {
                    throw new ArgumentNullException($"Failed get Patient Profile data ID = {Id} due no data in API or API connection error");
                }

                VMPatientProfile? data = JsonConvert.DeserializeObject<VMPatientProfile>(apiBiodataResponse.data.ToString());
                ViewBag.Account = JsonConvert.DeserializeObject<VMUser>(apiUserResponse.data.ToString());
                ViewBag.BiodataId = HttpContext.Session.GetString("BiodataID");

                return View(data);

            }
            catch (Exception e)
            {
                HttpContext.Session.SetString("ErrMsg", e.Message);
                return View();
            }
        }

        public async Task<IActionResult> PatientEditBio(int Id)
        {
            try
            {
                VMResponse? apiBiodataResponse = JsonConvert.DeserializeObject<VMResponse>(
                                    await httpClient.GetStringAsync(apiUrl + "PatientProfile/" + Id));

                if (apiBiodataResponse == null)
                {
                    throw new ArgumentNullException($"Failed get Biodata data ID = {Id}, and API connection Error");
                }

                if (apiBiodataResponse.data != null || apiBiodataResponse.Success)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiBiodataResponse.Message);
                }
                else
                {
                    throw new ArgumentNullException($"Failed get variant data ID = {Id} due no data in API or API connection error");
                }
                VMPatientProfile? data = JsonConvert.DeserializeObject<VMPatientProfile>(apiBiodataResponse.data.ToString());
 

                return View(data);

            }
            catch (Exception e)
            {
                HttpContext.Session.SetString("ErrMsg", e.Message);
                return View();
            }

        }

        [HttpPost]
        public async Task<VMResponse> PatientEditBio(VMPatientProfile biodata)
        {
            VMResponse? apiResponse = new VMResponse();

            try
            {
                string jsonData = JsonConvert.SerializeObject(biodata);

                HttpContent content = new StringContent(jsonData, Encoding.UTF8, "application/Json");

                apiResponse = JsonConvert.DeserializeObject<VMResponse>(await (
                    await httpClient.PutAsync(apiUrl + "PatientProfile/CreateUpdate", content)
                    ).Content.ReadAsStringAsync());


                if (apiResponse == null)
                {
                    throw new ArgumentNullException("ErrMsg", $"Failed update Biodata ID = {0} due API Connection Error!");
                }

                if (apiResponse.Success || apiResponse.data != null)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiResponse.Message);
                }
                else
                { throw new ArgumentNullException($"Cannot update Biodata ID = {0} because failed to get data from API!"); }

                // return View(apiResponse);

            }

            catch (Exception e)
            {
                HttpContext.Session.SetString("ErrMsg", $"Failed Update Biodata ID = {0} due API Connection Error!");
                apiResponse.Success = false;
                apiResponse.Message = e.Message;
                apiResponse.data = null;
                return apiResponse;
			}

			HttpContext.Session.SetString("FullName", biodata.Fullname);
			return apiResponse;

        }

        public async Task<IActionResult> PatientEditEmail(int Id)
        {
            try
            {
                VMResponse? apiAccountResponse = JsonConvert.DeserializeObject<VMResponse>(
                                    await httpClient.GetStringAsync(apiUrl + "User/" + Id));

                if (apiAccountResponse == null)
                {
                    throw new ArgumentNullException($"Failed get User data ID = {Id}, and API connection Error");
                }

                if (apiAccountResponse.data != null || apiAccountResponse.Success)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiAccountResponse.Message);
                }
                else
                {
                    throw new ArgumentNullException($"Failed get User data ID = {Id} due no data in API or API connection error");
                }
                VMUser? data = JsonConvert.DeserializeObject<VMUser>(apiAccountResponse.data.ToString());


                return View(data);

            }
            catch (Exception e)
            {
                HttpContext.Session.SetString("ErrMsg", e.Message);
                return View();
            }

        }

        [HttpPost]
        public async Task<VMResponse> PatientEditEmail(VMUser emailPatient)
        {
            VMResponse? apiResponse = new VMResponse();

            try
            {
                string jsonData = JsonConvert.SerializeObject(emailPatient);

                HttpContent content = new StringContent(jsonData, Encoding.UTF8, "application/Json");

                apiResponse = JsonConvert.DeserializeObject<VMResponse>(await (
                    await httpClient.PutAsync(apiUrl + "User/Update", content)
                    ).Content.ReadAsStringAsync());


                if (apiResponse == null)
                {
                    throw new ArgumentNullException("ErrMsg", $"Failed update User ID = {0} due API Connection Error!");
                }

                if (apiResponse.Success || apiResponse.data != null)
                {
                    //HttpContext.Session.SetString("InfoMsg", apiResponse.Message);
                }
                else
                { throw new ArgumentNullException($"Cannot update User ID = {0} because failed to get data from API!"); }

                // return View(apiResponse);

            }

            catch (Exception e)
            {
                HttpContext.Session.SetString("ErrMsg", $"Failed Update User ID = {0} due API Connection Error!");
                apiResponse.Success = false;
                apiResponse.Message = e.Message;
                apiResponse.data = null;
                return apiResponse;
            }
            return apiResponse;

        }


        public async Task<IActionResult> PatientEditPassword(int Id)
        {

            try
            {
                VMResponse? apiAccountResponse = JsonConvert.DeserializeObject<VMResponse>(
                                    await httpClient.GetStringAsync(apiUrl + "User/" + Id));

                if (apiAccountResponse == null)
                {
                    throw new ArgumentNullException($"Failed get User data ID = {Id}, and API connection Error");
                }

Med322/Views/Shared/_Alert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{


    ViewBag.InfoMsg = Context.Session.GetString("InfoMsg") ?? String.Empty;
    ViewBag.WarnMsg = Context.Session.GetString("WarnMsg") ?? String.Empty;
    ViewBag.ErrMsg = Context.Session.GetString("ErrMsg") ?? String.Empty;

    Context.Session.SetString("InfoMsg", string.Empty);
    Context.Session.SetString("WarnMsg", string.Empty);
    Context.Session.SetString("ErrMsg", string.Empty);

}
<div id="alertPlaceholder" class="alert alert-dismissible m-auto p-0" role="alert" aria-hidden="true"></div>


<script>
    $(document).ready(function () {
        function alertPopup(msg, type) {
            $("#alertPlaceholder").append(
                '<div class="alert alert-' + type + '">'
                + '<i class="fas fa-info-circle text-' + type + ' mr-2"></i>' + msg
                + '<button type="button" class="justify-content-between btn-close btn-primary rounded float-right" data-bs-dismiss="alert" aria-label="close">'
                + '<span aria-hidden="true">&times;</span>'
                + '</button></div>')
        }
        if ("@ViewBag.InfoMsg" != "") alertPopup("@Html.Raw(ViewBag.InfoMsg)", "info")
        if ("@ViewBag.WarnMsg" != "") alertPopup("@Html.Raw(ViewBag.WarnMsg)", "warning")
        if ("@ViewBag.ErrMsg" != "") alertPopup("@Html.Raw(ViewBag.ErrMsg)", "danger")
    });
</script>

Med322/Views/Shared/_Find.cshtml
@using Med322.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<form id="EditSpecialization" data-doctorid="@Model.Id" method="post" asp-controller="Doctor" asp-action="specialization">
    <input type="hidden" id="doctor" name="Id" value="@Model.Id"></input>
    <input type="hidden" name="ModifiedBy" value="@Model.Id"></input>
    <div class="card">
        <div class="card-header h3">Find Doctor</div>
        <div class="card-body">
            <div class="row">
                <label class="form-label">Lokasi</label>
                @*<input class="form-control" type="text" name="CategoryId"></input>*@
                <select class="form-control" name="Str">
                    <option value="">--Select Category--</option>
                    @foreach (VMMSpecialization specialization in ViewBag.Specialization)
                    {
                            <option value="@specialization.Name">@specialization.Name</option>
                    }
                </select>
            </div>
            <div class="row">
                <label class="form-label">Nama Dokter</label>
                <input class="form-control" type="text" name=""></input>                
            </div>
            <div class="row">
                <label class="form-label">Spesialisasi*</label>
                @*<input class="form-control" type="text" name="CategoryId"></input>*@
                <select class="form-control" name="Str">
                    <option value="">--Select Category--</option>
                    @foreach (VMMSpecialization specialization in ViewBag.Specialization)
                    {
                            <option value="@specialization.Name">@specialization.Name</option>
                    }
                </select>
            </div>
            <div class="row">
                <label class="form-label">Tindakan Medis</label>
                @*<input class="form-control" type="text" name="CategoryId"></input>*@
                <select class="form-control" name="Str">
                    <option value="">--Select Category--</option>
                    @foreach (VMMSpecialization specialization in ViewBag.Specialization)
                    {
                            <option value="@specialization.Name">@specialization.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between">
                &nbsp;
                <button type="submit" class="btn btn-info float-end"><i class="ti-search"></i> Cari</button>
            </div>
        </div>
    </div>
</form>

Med322/Views/Shared/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MedId</title>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <!--bootstrap-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- End custom js for this page-->
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/skydash/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/skydash/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/skydash/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/skydash/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/skydash/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/skydash/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/skydash/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="images/favicon.png" />
</head>

Med322/Views/Shared/_JqueryPlugin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- plugins:js -->
<script src="~/skydash/vendors/js/vendor.bundle.base.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="~/skydash/vendors/chart.js/Chart.min.js"></script>
<script src="~/skydash/vendors/datatables.net/jquery.dataTables.js"></script>
<script src="~/skydash/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
<script src="~/skydash/js/dataTables.select.min.js"></script>

<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="~/skydash/js/off-canvas.js"></script>
<script src="~/skydash/js/hoverable-collapse.js"></script>
<script src="~/skydash/js/template.js"></script>
<script src="~/skydash/js/settings.js"></script>
<script src="~/skydash/js/todolist.js"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="~/skydash/js/dashboard.js"></script>
<script src="~/skydash/js/Chart.roundedBarCharts.js"></script>
<!-- End custom js for this page-->

Med322/Views/Shared/_LayoutMedId.cshtml
@{
    ViewBag.User = Context.Session.GetString("RoleName") ?? "Guest";

    ViewBag.UserName = Context.Session.GetString("FullName") ?? "Guest";

    if (Context.Session.GetString("FullName") == "Guest" && Context.Session.GetString("RoleName") != "Guest")
    {
        ViewBag.UserName = Context.Session.GetString("RoleName");
    }

    ViewBag.Doctor = Context.Session.GetString("DoctorId") ?? "0";


}
<!DOCTYPE html>
<html lang="en">

<partial name="_Header" />
<partial name="_JqueryPlugin" />

<body>

    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo mr-5" asp-action="Index" asp-controller="@ViewBag.User"><img src="~/Images/Logo.png" class="mr-2" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" asp-action="Index" asp-controller="@ViewBag.User"><img src="~/Images/LogoMini.png" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                @if (ViewBag.User != "Guest")
                {
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="icon-menu"></span>
                    </button>
                }
                <ul class="navbar-nav mr-lg-2">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                                <span class="input-group-text" id="search">
                                    <i class="icon-search"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="navbar-search-input" placeholder="Cari Dokter atau Obat" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                @*Pakai Topbar yang ini*@
                @if (ViewBag.User != "Guest")
                {
                    <ul class="navbar-nav navbar-nav-right">
                        <li class="nav-item">
                            <div>Hello, @ViewBag.UserName</div>
                        </li>
                        <li class="nav-item nav-profile dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="profileDropdown">
                                <img src="~/skydash/images/faces/face28.jpg" alt="profile" />
                            </a>
                            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                                @if (ViewBag.User == "Patient")
                                {
                                    <a class="dropdown-item" asp-action="Index" asp-controller="ProfilePatient">
                                        <i class="ti-user text-primary"></i>
                                        Profile @ViewBag.User
                                    </a>
                                }
                                else if (ViewBag.User == "Doctor")
                                {
                                    <a class="dropdown-item" asp-action="ProfileDoctor" asp-controller="Doctor">
                                        <i class="ti-user text-primary"></i>
                                        Profile @ViewBag.User
                                    </a>
                                    <a class="dropdown-item" asp-action="profile" asp-controller="Doctor" asp-route-id="@ViewBag.Doctor">
                                        <i class="ti-user text-primary"></i>
                                        Doctor Profile Shared
                                    </a>
                                }
                                <a class="dropdown-item" asp-action="Logout" asp-controller="Login">
                                    <i class="ti-power-off text-primary"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav navbar-nav-right">
                        <li class="nav-item">
                            @*                            <a asp-action="Index" asp-controller="Login" class="btn btn-info btn-rounded btn-md mr-2">Masuk</a>*@
                            <button id="btnMasuk" type="button" class="btn btn-info btn-rounded btn-md mr-2">Masuk</button>
                            <a asp-action="SignIn" asp-controller="Login" class="btn btn-secondary btn-rounded btn-md">Daftar</a>
                        </li>
                    </ul>
                }
            </div>
        </nav>
        <partial name="_Modal" />
        <!-- partial -->
        @if (@ViewBag.User != "Guest")
        {
            <div class="container-fluid page-body-wrapper">
                <!-- partial:partials/_settings-panel.html -->
                <!-- partial:partials/_sidebar.html -->

                <partial name="_Sidebar" />

                <!-- partial -->
                <div class="main-panel">

                    <div class="content-wrapper container-fluid">
                        <partial name="_Alert" />
                        <partial name="_Modal" />
                        @RenderBody()
                    </div>
                    <!-- content-wrapper ends -->
                    <!-- partial:partials/_footer.html -->
                    <footer class="footer">
                        <div class="d-sm-flex justify-content-center justify-content-sm-between">
                            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span>
                        </div>
                        <div class="d-sm-flex justify-content-center justify-content-sm-between">
                            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Distributed by <a href="https://www.themewagon.com/" target="_blank">Themewagon</a></span>
                        </div>
                    </footer>
                    <!-- partial -->
                </div>

                <!-- main-panel ends -->
            </div>
        }
        else
        {
            <div class="content-wrapper container-fluid">
                <div class="content-wrapper container-fluid">
                    <partial name="_Alert" />
                    <partial name="_Modal" />
                    @RenderBody()
                </div>

                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span>
                    </div>
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Distributed by <a href="https://www.themewagon.com/" target="_blank">Themewagon</a></span>
                    </div>
                </footer>
            </div>
        }
        <!-- page-body-wrapper ends -->
    </div>

</body>

</html>

<script>

    $(document).ready(function () {
        $("#btnMasuk").click(function () {
            debugger;
            $("#myModalBody").load("Login/Index")
            $("#myModal").modal("show");
        });
    });

</script>